import type {
  Crop,
  Expense,
  MandiPrice,
  Scheme,
  SoilReading,
  WeatherBundle,
} from './types';

/**
 * Offline seed data.
 *
 * This is what the app shows when the device has no network and no cache yet —
 * a farmer opening KrishiSathi in a dead zone still sees a working dashboard
 * instead of six spinners. Every value here is overwritten by live data the
 * moment a request succeeds.
 */

export const DEMO_CROPS: Crop[] = [
  {
    id: 'wheat',
    name: 'Wheat',
    emoji: '🌾',
    areaAcre: 2.5,
    stage: 'Vegetative growth',
    signal: 'green',
    status: 'Healthy',
    nextAction: 'Top dress urea',
    nextActionIn: 'in 4 days',
    sownOn: '2025-11-12',
    expectedYieldQtl: 46,
    yieldTrend: 6.2,
  },
  {
    id: 'tomato',
    name: 'Tomato',
    emoji: '🍅',
    areaAcre: 0.8,
    stage: 'Flowering',
    signal: 'red',
    status: 'At risk',
    nextAction: 'Spray for early blight',
    nextActionIn: 'today',
    sownOn: '2025-12-02',
    expectedYieldQtl: 62,
    yieldTrend: -4.5,
  },
  {
    id: 'sugarcane',
    name: 'Sugarcane',
    emoji: '🎋',
    areaAcre: 1.2,
    stage: 'Harvest ready',
    signal: 'yellow',
    status: 'Watch',
    nextAction: 'Book harvest slot',
    nextActionIn: 'in 9 days',
    sownOn: '2025-02-18',
    expectedYieldQtl: 480,
    yieldTrend: 2.1,
  },
];

export const DEMO_WEATHER: WeatherBundle = {
  now: {
    tempC: 31,
    feelsLikeC: 34,
    humidity: 68,
    windKph: 12,
    rainChance: 80,
    condition: 'Humid, rain likely',
    icon: '10d',
    place: 'Nashik, Maharashtra',
  },
  forecast: [
    { day: 'Today', date: '', maxC: 31, minC: 21, rainChance: 80, condition: 'Rain', icon: '10d' },
    { day: 'Tue', date: '', maxC: 29, minC: 20, rainChance: 65, condition: 'Showers', icon: '09d' },
    { day: 'Wed', date: '', maxC: 32, minC: 21, rainChance: 20, condition: 'Cloudy', icon: '03d' },
    { day: 'Thu', date: '', maxC: 34, minC: 22, rainChance: 10, condition: 'Sunny', icon: '01d' },
    { day: 'Fri', date: '', maxC: 33, minC: 22, rainChance: 15, condition: 'Sunny', icon: '02d' },
  ],
  irrigation: {
    signal: 'green',
    kind: 'skip',
    rainChance: 80,
    tempC: 31,
    humidity: 68,
    headline: 'Skip watering today',
    detail: '80% chance of rain in the next 24 hours. Your wheat block does not need irrigation.',
    litresSaved: 4200,
  },
};

export const DEMO_MANDI: MandiPrice[] = [
  {
    id: 'wheat-nashik',
    commodity: 'Wheat',
    emoji: '🌾',
    market: 'Nashik APMC',
    district: 'Nashik',
    state: 'Maharashtra',
    modalPrice: 2450,
    minPrice: 2310,
    maxPrice: 2580,
    changePct: 3.2,
    unit: 'quintal',
    congestion: 'green',
    waitMinutes: 25,
    distanceKm: 14,
    updatedAt: 'today',
  },
  {
    id: 'onion-lasalgaon',
    commodity: 'Onion',
    emoji: '🧅',
    market: 'Lasalgaon',
    district: 'Nashik',
    state: 'Maharashtra',
    modalPrice: 1780,
    minPrice: 1500,
    maxPrice: 2050,
    changePct: 4.1,
    unit: 'quintal',
    congestion: 'red',
    waitMinutes: 190,
    distanceKm: 38,
    updatedAt: 'today',
  },
  {
    id: 'tomato-pune',
    commodity: 'Tomato',
    emoji: '🍅',
    market: 'Pune Market',
    district: 'Pune',
    state: 'Maharashtra',
    modalPrice: 2120,
    minPrice: 1850,
    maxPrice: 2400,
    changePct: 8.6,
    unit: 'quintal',
    congestion: 'yellow',
    waitMinutes: 95,
    distanceKm: 162,
    updatedAt: 'today',
  },
  {
    id: 'soybean-latur',
    commodity: 'Soybean',
    emoji: '🫘',
    market: 'Latur APMC',
    district: 'Latur',
    state: 'Maharashtra',
    modalPrice: 4630,
    minPrice: 4400,
    maxPrice: 4820,
    changePct: -1.4,
    unit: 'quintal',
    congestion: 'green',
    waitMinutes: 30,
    distanceKm: 210,
    updatedAt: 'today',
  },
  {
    id: 'cotton-akola',
    commodity: 'Cotton',
    emoji: '🪴',
    market: 'Akola APMC',
    district: 'Akola',
    state: 'Maharashtra',
    modalPrice: 7280,
    minPrice: 6900,
    maxPrice: 7550,
    changePct: 0.8,
    unit: 'quintal',
    congestion: 'green',
    waitMinutes: 40,
    distanceKm: 320,
    updatedAt: 'today',
  },
  {
    id: 'gram-jalna',
    commodity: 'Gram',
    emoji: '🌰',
    market: 'Jalna APMC',
    district: 'Jalna',
    state: 'Maharashtra',
    modalPrice: 5340,
    minPrice: 5100,
    maxPrice: 5600,
    changePct: 2.1,
    unit: 'quintal',
    congestion: 'yellow',
    waitMinutes: 80,
    distanceKm: 175,
    updatedAt: 'today',
  },
];

export const DEMO_SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    name: 'PM-KISAN',
    nameHi: 'पीएम किसान सम्मान निधि',
    benefit: '₹6,000 / year',
    category: 'Direct income',
    eligible: true,
    reason: 'Landholding under 2 ha and Aadhaar-linked bank account on file.',
    applyUrl: 'https://pmkisan.gov.in/',
    documents: ['Aadhaar card', 'Land record (7/12)', 'Bank passbook'],
  },
  {
    id: 'fasal-bima',
    name: 'PM Fasal Bima Yojana',
    nameHi: 'प्रधानमंत्री फसल बीमा योजना',
    benefit: 'Crop insurance from 2% premium',
    category: 'Insurance',
    eligible: true,
    reason: 'Wheat and tomato are both notified crops in your district this season.',
    deadline: '31 Dec',
    applyUrl: 'https://pmfby.gov.in/',
    documents: ['Aadhaar card', 'Sowing certificate', 'Bank passbook'],
  },
  {
    id: 'kcc',
    name: 'Kisan Credit Card',
    nameHi: 'किसान क्रेडिट कार्ड',
    benefit: 'Up to ₹3 lakh @ 4%',
    category: 'Credit',
    eligible: true,
    reason: 'Any cultivator with land records qualifies; interest subvention applies below ₹3 lakh.',
    applyUrl: 'https://www.myscheme.gov.in/schemes/kcc',
    documents: ['Aadhaar card', 'Land record', 'Passport photo'],
  },
  {
    id: 'kusum',
    name: 'PM Kusum Solar Pump',
    nameHi: 'पीएम कुसुम सोलर पंप',
    benefit: '60% subsidy on solar pump',
    category: 'Energy',
    eligible: false,
    reason: 'Your holding already has a grid-connected electric pump registered.',
    applyUrl: 'https://pmkusum.mnre.gov.in/',
    documents: ['Aadhaar card', 'Land record', 'Electricity bill'],
  },
  {
    id: 'shc',
    name: 'Soil Health Card',
    nameHi: 'मृदा स्वास्थ्य कार्ड',
    benefit: 'Free soil test every 2 years',
    category: 'Advisory',
    eligible: true,
    reason: 'Your last recorded soil test is more than 24 months old.',
    applyUrl: 'https://soilhealth.dac.gov.in/',
    documents: ['Aadhaar card', 'Land record'],
  },
  {
    id: 'enam',
    name: 'e-NAM Registration',
    nameHi: 'ई-नाम पंजीकरण',
    benefit: 'Sell to 1,000+ mandis online',
    category: 'Market',
    eligible: true,
    reason: 'Nashik APMC is an e-NAM linked yard — you can bid without travelling.',
    applyUrl: 'https://enam.gov.in/',
    documents: ['Aadhaar card', 'Bank passbook', 'Mobile number'],
  },
];

export const DEMO_SOIL: SoilReading = {
  nitrogen: { value: 210, signal: 'red', label: 'Low' },
  phosphorus: { value: 24, signal: 'green', label: 'Good' },
  potassium: { value: 168, signal: 'yellow', label: 'Medium' },
  ph: { value: 6.8, signal: 'green', label: 'Neutral' },
  organicCarbon: { value: 0.42, signal: 'yellow', label: 'Medium' },
  advice: [
    'Apply 45 kg urea per acre in two splits — nitrogen is the limiting nutrient this season.',
    'Potassium is borderline. Add 20 kg MOP per acre before the next irrigation.',
    'Grow dhaincha as a green manure after harvest to lift organic carbon above 0.5%.',
  ],
};

export const DEMO_EXPENSES: Expense[] = [
  { id: 'e1', label: 'Wheat seed (certified)', category: 'seed', amount: 6800, date: '2025-11-10' },
  { id: 'e2', label: 'DAP 2 bags', category: 'fertiliser', amount: 2900, date: '2025-11-14' },
  { id: 'e3', label: 'Sowing labour', category: 'labour', amount: 4200, date: '2025-11-12' },
  { id: 'e4', label: 'Diesel for pump', category: 'fuel', amount: 1850, date: '2025-12-01' },
  { id: 'e5', label: 'Urea top dressing', category: 'fertiliser', amount: 1450, date: '2025-12-20' },
  { id: 'e6', label: 'Tomato sale — Pune', category: 'income', amount: 21400, date: '2026-01-08' },
  { id: 'e7', label: 'Weeding labour', category: 'labour', amount: 3100, date: '2026-01-11' },
  { id: 'e8', label: 'Wheat sale — Nashik APMC', category: 'income', amount: 49000, date: '2026-01-26' },
];

/** Known-good registration prefixes used by the offline counterfeit heuristic. */
export const KNOWN_INPUT_BRANDS = [
  'IFFCO',
  'Coromandel',
  'Rallis',
  'UPL',
  'Bayer',
  'Syngenta',
  'Dhanuka',
  'Tata Rallis',
  'Nagarjuna',
  'Chambal',
];

export const HELPLINES = [
  { id: 'kisan', label: 'Kisan Call Centre', number: '18001801551', emoji: '📞', note: '6am – 10pm, all languages' },
  { id: 'vet', label: 'Animal husbandry', number: '1962', emoji: '🐄', note: 'Mobile veterinary unit' },
  { id: 'ambulance', label: 'Ambulance', number: '108', emoji: '🚑', note: 'Medical emergency' },
  { id: 'police', label: 'Police', number: '112', emoji: '🚓', note: 'All-India emergency' },
  { id: 'disaster', label: 'Disaster helpline', number: '1077', emoji: '🌊', note: 'District control room' },
  { id: 'poison', label: 'Pesticide poisoning', number: '1800116117', emoji: '☠️', note: 'National poison centre' },
];
